### ISSUE TITLE
meltano config tap-smoke-test set --interactive doesnt work well

### ISSUE THREAD

**Issue by jfo8001** [meltano/tap-smoke-test#95]
I was trying to use this for some sample data and it was nearly impossible to choose a stream inside of the interactive configurator - I had to fall back to using meltano to copy paste. 

```meltano config tap-smoke-test set --interactive```
Choose option 10 (streams)

<img width="838" alt="image" src="https://github.com/meltano/tap-smoke-test/assets/106567118/23ea575a-14d8-4d22-bd0a-dc40c36b3c6b">

```[ {"animals", "https://raw.githubusercontent.com/meltano/tap-smoke-test/main/demo-data/animals-data.jsonl"}]```

I tried passing it an array of objects, like the instructions said, and it did not wind up like the example in the getting started tutorial at all
https://docs.meltano.com/cloud/getting_started/#new-to-meltano

Given this is in the getting started guide - perhaps some love and attention to the interactive config would be nice?

**Comment by edgarrmondragon** [comment]
Thanks for reporting @jfo8001!

I think the error here is the input format, since you're inputting two array elements each with one key, instead of a single element with two keys:

```diff
- [ {"stream_name": "animals"}, {"input_filename": "https://raw.githubusercontent.com/meltano/tap-smoke-test/main/demo-data/animals-data.jsonl"}]
+ [ {"stream_name": "animals", "input_filename": "https://raw.githubusercontent.com/meltano/tap-smoke-test/main/demo-data/animals-data.jsonl"}]
```

This produces what I think is the correct setting value:

```yaml
extractors:
  - name: tap-smoke-test
    variant: meltano
    pip_url: git+https://github.com/meltano/tap-smoke-test.git
    config:
      streams:
        - stream_name: animals
          input_filename: https://raw.githubusercontent.com/meltano/tap-smoke-test/main/demo-data/animals-data.jsonl
```

The "Getting Started" guide could certainly be improved, PRs welcome!
